wdhdev/free-for-life

README.md

(I hope the formatting isn't broken, because I had to do this on mobile)

Adds Excalidraw under the design category

---

README.md

I've included [ProtonMail](https://proton.me/mail) in the list of email services. It's an excellent choice if you're looking for a service that prioritizes privacy.

Add ProtonMail

---

README.md

I've included [Nerd Fonts](https://www.nerdfonts.com/) in the list of fonts.

Add Nerd Fonts

---

README.md

I've included [Code Whisper](https://aws.amazon.com/codewhisperer/) and [Bard AI](https://bard.google.com/) to the list.

Add Bard AI and Code Whisper

---

README.md

I've included several websites to the list. 
- [Lunacy](https://icons8.com/lunacy)
- [Microsoft Azure](https://azure.microsoft.com)
- [Google Public DNS](https://developers.google.com/speed/public-dns)
- [Google Forms](https://docs.google.com/forms)

Add several websites

---

README.md

I've included some websites to list.
- [Devicons](https://vorillaz.github.io/devicons)
- [Font Awesome](https://fontawesome.com)

May 15 2023: Add several websites

---

README.md

I've included several websites to the list.
- [Brackets](https://brackets.io) 
- [Code::Blocks:](https://www.codeblocks.org)
- [Helix](https://helix-editor.com) 
- [Nano](https://www.nano-editor.org) 
- [Vim](https://www.vim.org) 
- [AdGuard DNS](https://adguard-dns.io)
- [OpenDNS](https://www.opendns.com)

May 16 2023: Add several websites

---

README.md

I've included a few websites to the list:
- [Appwrite](https://appwrite.io)
- [AWS Amplify](https://aws.amazon.com/amplify)
- [Kuzzle](https://kuzzle.io)
- [Microsoft Azure Mobile Apps](https://azure.microsoft.com/en-us/solutions/mobile)

May 19 2023: Add several websites

---

data/Databases.md

For some reason, likely an editing error when adding AppWrite, a duplicate of Firebase was added. This commit removes the erroneous line from the source material.

Remove Duplicate of Firebase

---

data/Email.md

added several services
Tutanota is a privacy oriented services similar to ProtonMail.
Tempail and TempMail are both temporary/disposable email services but since there are probably at least a hundred out there from a search, they could be redundant and removed.

Update Email.md - add 3 services

---

README.md

Preferably get rid of Ubuntu and Kubuntu as those are super-bloated, however decided to not do it myself as you might want these to stay there.

Added an epic DNS service + updated linux distro list

---

data/Artificial_Intelligence.md
data/Domains.md
data/Linux_Distributions.md

New Services

---

data/Code_Editors.md
data/Linux_Distributions.md
data/SSL.md

Added new services & category.

New Category & Services

---

README.md

Red Hat Enterprise Linux it's not free , you need subscription to use it.
Free as in you can download the source yes. All Linux is, Red hat support, services and extras however are not free forever.
without subscription you can't update the packages.

Red Hat Enterprise Linux it's not free  forever

---

data/SSL.md

- Added [ZeroSSL](https://zerossl.com) to the SSL section

Added ZeroSSL

---

README.md
data/Payments_and_Billing.md

Add Paymenter

---

README.md

Ref: https://github.com/publicsuffix/list/pull/1798

getlocalcert.net domains are now on the PSL

---

data/Domains.md

Added the free subdomain service, obl.ong to the "domains" section.

Added obl.ong

---

data/Artificial_Intelligence.md
data/Code_Editors.md
data/Code_Generation.md

Add huggingface, onlinegdb and blackbox ai

Add 3 Sites

---

data/Course.md
data/Courses.md
data/_start.md

I think such a category is necessary. I also added the Hackerrank site

Add course category

---

README.md
data/For_Students.md

Added roadmap.sh to the `For Students` section as it's #6 on GH and widely regarded a great resource for learning anything developer related.

add roadmap.sh to 'for students' section

---

data/Domains.md

I would like to add my free domain to the list. Thanks.

Add 'thedev.me' to Domains.md

---

data/PaaS.md

Added Replit to the `data/paas.md` file.

Add Replit to PaaS

---

data/APIs_Data_and_ML.md

Add Mockae, an open source Fake REST API powered by Lua, to APIs, Data and ML

Add Mockae to APIs, Data and ML

---

data/DNS.md

Control-D   (NextDNS alternative)
https://controld.com/free-dns

add Control-D Free DNS

---

data/Email.md

AdGuard Temp Mail
https://adguard.com/en/adguard-temp-mail/overview.html

add AdGuard Temp Mail

---

data/Domains.md

add open host

---

data/SSL.md

https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html
https://wiki.mozilla.org/CA/WoSign_Issues

delete WoSign SSL

---

data/Courses.md

add freeCodeCamp

---

data/DNS.md

both named FreeDNS, but they are different companies

add 1984 Hosting FreeDNS and Afraid.org FreeDNS

---

data/Design_and_UI.md

Undraw provides free and customizable illustrations.

unDraw - Open source illustrations

---

data/Payments_and_Billing.md

[https://www.ambeteco.com/ParityVend/](https://www.ambeteco.com/ParityVend/)

Add ParityVend

---

data/APIs_Data_and_ML.md

Add JSONing to APIs_Data_and_ML.md

Add JSONing

---

data/Forms.md

Add Formbricks and Refactor Descriptions for Formpost, Form-data and Formingo

---

README.md

Reverts wdhdev/free-for-life#103

Revert "Add Zone.ID to Domains"

---

README.md
data/Domains.md

From pull request #103, now the data is also updated.

Add Zone.ID to Domains (2)

---

data/Payments_and_Billing.md

Added Xendit.co in Payments and Billing

---

data/Artificial_Intelligence.md
data/Code_Generation.md

Added Claude and Mistral to AI
Added Bolt and Lovable to Code Generation

Added Claude,Mistral,Lovable and Bolt

---

data/Email.md
data/Linux_Distributions.md

This pull request updates the documentation files:
Email.md
Added details about mail.tm and mail.gw disposable email services.
Linux_Distributions.md
Added Garuda Linux to the list of Linux distributions.

Updated Email.md and Linux_Distributions.md

---

data/Artificial_Intelligence.md
data/Calendar.md
data/Design_and_UI.md
data/Linux_Distributions.md

Added new things and also put some things in alphabetical order
- Proton Calendar
- Lumo
- Photopea
- AnduinOS

Added new things
